// Generator for the reference Muscle Atlas artwork data.
//
// Reads the vendored reference SVGs (`lib/atlas/reference/{male,female}-body.svg`, used with the
// author's permission — see reference/NOTICE.md), splits each into its front/back nested-svg
// halves, and emits `reference-data.ts`: per gender, per half, the muscle path `d` strings tagged
// with the source `data-muscle` label, plus each half's viewBox. Deterministic, so re-running with
// unchanged SVGs produces byte-identical output. Run with:
//
//   node apps/web/scripts/generate-reference-atlas.mts
//
// (Node 22+ runs the TypeScript directly.) Commit the regenerated reference-data.ts.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const refDir = join(here, "..", "lib", "atlas", "reference");

type Half = "front" | "back";
interface RefPath {
  muscle: string;
  d: string;
}

function halves(svg: string): { front: { viewBox: string; paths: RefPath[] }; back: { viewBox: string; paths: RefPath[] } } {
  // The combined figure holds two nested <svg> — front (x="0…") then back (x="395…").
  const backIdx = svg.indexOf('<svg x="395"');
  const frontChunk = svg.slice(svg.indexOf('<svg x="0"'), backIdx);
  const backChunk = svg.slice(backIdx);
  return { front: parseHalf(frontChunk), back: parseHalf(backChunk) };
}

// The x-extent of a path. The reference uses only absolute M/L/C/V/Z, so x values are every other
// number of an M/L/C parameter run; V carries a lone y and contributes no x. Parsed by command
// rather than by naive alternation, which V would otherwise throw off.
function xExtent(d: string): { min: number; max: number } {
  const tokens = d.match(/[A-Za-z]|-?\d*\.?\d+(?:e[-+]?\d+)?/gi) ?? [];
  let min = Infinity;
  let max = -Infinity;
  let command = "";
  let paramIndex = 0;
  for (const token of tokens) {
    if (/[A-Za-z]/.test(token)) {
      command = token.toUpperCase();
      paramIndex = 0;
      continue;
    }
    const value = Number(token);
    // M, L and C take (x, y) pairs — x sits at every even parameter index.
    if ((command === "M" || command === "L" || command === "C") && paramIndex % 2 === 0) {
      if (value < min) min = value;
      if (value > max) max = value;
    }
    paramIndex += 1;
  }
  return { min, max };
}

// Each nested <svg> in the source carries the paths of BOTH figures and relies on its own viewBox
// plus overflow="hidden" to crop to its half. We keep only the paths that actually belong to this
// half — the ones whose horizontal centre falls inside its viewBox — so the emitted data is the
// half itself rather than a full canvas that only looks right when clipped.
function belongsToHalf(d: string, viewBox: string): boolean {
  const [vx, , vw] = viewBox.split(/\s+/).map(Number);
  const { min, max } = xExtent(d);
  if (!Number.isFinite(min) || !Number.isFinite(max)) return false;
  const centre = (min + max) / 2;
  return centre >= vx && centre <= vx + vw;
}

function parseHalf(chunk: string): { viewBox: string; paths: RefPath[] } {
  const viewBox = /viewBox="([^"]*)"/.exec(chunk)?.[1] ?? "";
  const paths: RefPath[] = [];
  const re = /<path\b[^>]*?\/>/gs;
  let m: RegExpExecArray | null;
  while ((m = re.exec(chunk))) {
    const tag = m[0];
    const d = /\sd="([^"]*)"/.exec(tag)?.[1];
    const muscle = /data-muscle="([^"]*)"/.exec(tag)?.[1] ?? "unknown";
    if (d && belongsToHalf(d, viewBox)) paths.push({ muscle, d });
  }
  return { viewBox, paths };
}

const genders = ["male", "female"] as const;
const data: Record<string, ReturnType<typeof halves>> = {};
for (const g of genders) {
  data[g] = halves(readFileSync(join(refDir, `${g}-body.svg`), "utf8"));
}

const viewBox: Record<string, Record<Half, string>> = {};
const paths: Record<string, Record<Half, RefPath[]>> = {};
for (const g of genders) {
  viewBox[g] = { front: data[g].front.viewBox, back: data[g].back.viewBox };
  paths[g] = { front: data[g].front.paths, back: data[g].back.paths };
}

const out = `// GENERATED by scripts/generate-reference-atlas.mts — do not edit by hand.
//
// The reference Muscle Atlas artwork (Olkre/Sasha-s-Body-Map), used with the author's permission
// (see reference/NOTICE.md), split into front/back halves per gender. The app renders these path
// \`d\` strings recolored by our own coverage data; \`muscle\` is the source region label, mapped to
// our canonical Muscle vocabulary by \`reference-muscle-map.ts\`.

export type ReferenceGender = "male" | "female";
export type ReferenceHalf = "front" | "back";

export interface ReferencePath {
  muscle: string;
  d: string;
}

export const REFERENCE_VIEWBOX: Record<ReferenceGender, Record<ReferenceHalf, string>> = ${JSON.stringify(
  viewBox,
  null,
  2,
)};

export const REFERENCE_PATHS: Record<ReferenceGender, Record<ReferenceHalf, ReferencePath[]>> = ${JSON.stringify(
  paths,
)};
`;

writeFileSync(join(refDir, "reference-data.ts"), out);
// eslint-disable-next-line no-console -- generator progress is intentional CLI output
console.log(
  `Wrote reference-data.ts: male ${paths.male.front.length}/${paths.male.back.length}, female ${paths.female.front.length}/${paths.female.back.length} front/back paths`,
);
