// Generator for the reference Muscle Atlas artwork data.
//
// Reads the vendored reference SVGs (`lib/atlas/reference/{male,female}-body.svg`, used with the
// author's permission — see reference/NOTICE.md), splits each into its front/back nested-svg
// halves, and emits `reference-data.ts`: per gender, per half, the muscle path `d` strings tagged
// with the source `data-muscle` label, plus each half's viewBox. Deterministic, so re-running with
// unchanged SVGs produces byte-identical output. Run with:
//
//   node apps/web/scripts/generate-reference-atlas.mts
//
// (Node 22+ runs the TypeScript directly.) Commit the regenerated reference-data.ts.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const refDir = join(here, "..", "lib", "atlas", "reference");

type Half = "front" | "back";
interface RefPath {
  muscle: string;
  d: string;
}

function halves(svg: string): { front: { viewBox: string; paths: RefPath[] }; back: { viewBox: string; paths: RefPath[] } } {
  // The combined figure holds two nested <svg> — front (x="0…") then back (x="395…").
  const backIdx = svg.indexOf('<svg x="395"');
  const frontChunk = svg.slice(svg.indexOf('<svg x="0"'), backIdx);
  const backChunk = svg.slice(backIdx);
  return { front: parseHalf(frontChunk), back: parseHalf(backChunk) };
}

function parseHalf(chunk: string): { viewBox: string; paths: RefPath[] } {
  const viewBox = /viewBox="([^"]*)"/.exec(chunk)?.[1] ?? "";
  const paths: RefPath[] = [];
  const re = /<path\b[^>]*?\/>/gs;
  let m: RegExpExecArray | null;
  while ((m = re.exec(chunk))) {
    const tag = m[0];
    const d = /\sd="([^"]*)"/.exec(tag)?.[1];
    const muscle = /data-muscle="([^"]*)"/.exec(tag)?.[1] ?? "unknown";
    if (d) paths.push({ muscle, d });
  }
  return { viewBox, paths };
}

const genders = ["male", "female"] as const;
const data: Record<string, ReturnType<typeof halves>> = {};
for (const g of genders) {
  data[g] = halves(readFileSync(join(refDir, `${g}-body.svg`), "utf8"));
}

const viewBox: Record<string, Record<Half, string>> = {};
const paths: Record<string, Record<Half, RefPath[]>> = {};
for (const g of genders) {
  viewBox[g] = { front: data[g].front.viewBox, back: data[g].back.viewBox };
  paths[g] = { front: data[g].front.paths, back: data[g].back.paths };
}

const out = `// GENERATED by scripts/generate-reference-atlas.mts — do not edit by hand.
//
// The reference Muscle Atlas artwork (Olkre/Sasha-s-Body-Map), used with the author's permission
// (see reference/NOTICE.md), split into front/back halves per gender. The app renders these path
// \`d\` strings recolored by our own coverage data; \`muscle\` is the source region label, mapped to
// our canonical Muscle vocabulary by \`reference-muscle-map.ts\`.

export type ReferenceGender = "male" | "female";
export type ReferenceHalf = "front" | "back";

export interface ReferencePath {
  muscle: string;
  d: string;
}

export const REFERENCE_VIEWBOX: Record<ReferenceGender, Record<ReferenceHalf, string>> = ${JSON.stringify(
  viewBox,
  null,
  2,
)};

export const REFERENCE_PATHS: Record<ReferenceGender, Record<ReferenceHalf, ReferencePath[]>> = ${JSON.stringify(
  paths,
)};
`;

writeFileSync(join(refDir, "reference-data.ts"), out);
// eslint-disable-next-line no-console -- generator progress is intentional CLI output
console.log(
  `Wrote reference-data.ts: male ${paths.male.front.length}/${paths.male.back.length}, female ${paths.female.front.length}/${paths.female.back.length} front/back paths`,
);
